spring:
  datasource:
    druid:
      url: ${MYSQL_JDBC_URL}
      username: ${MYSQL_USERNAME}
      password: ${MYSQL_PASSWORD}
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 1

logging:
  config: classpath:log4j2.xml
